name: Run examples

on:
  workflow_dispatch:

jobs:
  run_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: pyiron/actions/cached-miniforge@actions-3.2.0
        with:
          python-version: '3.11'
          env-files: .ci_support/environment.yml
          local-code-directory: ''
          use-cache: 'true'
          miniforge-activate-environment: poster-env
      - name: Add papermill and jupyter
        shell: bash -l {0}
        run: mamba install -n poster-env jupyter papermill
      - name: Execute workflow
        shell: bash -l {0}
        run: papermill examples.ipynb examples-out.ipynb
      - name: Upload updated notebook as artifact
        uses: actions/upload-artifact@v4
        with:
          name: examples-out.ipynb
          path: ./examples-out.ipynb